# Generated by Django 5.2.7 on 2025-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('computadora', 'Computadora'), ('smartphone', 'Smartphone'), ('audifonos', 'Audífonos'), ('tv', 'TV'), ('consola', 'Consola'), ('accesorio', 'Accesorio')], max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('sony', 'Sony'), ('logitech', 'Logitech'), ('xiaomi', 'Xiaomi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
