# Generated by Django 5.2.7 on 2025-10-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_categoria_producto_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('usado', 'Usado')], default='nuevo', max_length=5),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Computadora', 'Computadora'), ('Smartphone', 'Smartphone'), ('Audifonos', 'Audífonos'), ('TV', 'TV'), ('Consola', 'Consola'), ('Accesorio', 'Accesorio'), ('Microcontrolador', 'Microcontrolador')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Sony', 'Sony'), ('Logitech', 'Logitech'), ('Xiaomi', 'Xiaomi'), ('Arduino', 'Arduino')], max_length=20),
        ),
    ]
