# Generated by Django 5.2.7 on 2025-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('badge_text', models.CharField(blank=True, max_length=40)),
                ('badge_style', models.CharField(choices=[('solid', 'Sólido'), ('ghost', 'Ghost (borde claro)')], default='solid', max_length=10)),
                ('cta_text', models.CharField(default='Ver ofertas', max_length=40)),
                ('enlace', models.URLField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('gradiente_clase', models.CharField(blank=True, help_text='Ej: house, tennis, starlink, scooter, baby, kitchen', max_length=20)),
                ('texto_claro', models.BooleanField(default=False, help_text='Marcar si el texto debe ir claro (para fondos oscuros).')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={},
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Computadora', 'Computadora'), ('Laptop', 'Laptop'), ('Smartphone', 'Smartphone'), ('Tablet', 'Tablet'), ('Audifonos', 'Audífonos'), ('TV', 'Televisor'), ('Consola', 'Consola'), ('Videojuego', 'Videojuego'), ('Accesorio', 'Accesorio'), ('Microcontrolador', 'Microcontrolador'), ('Impresora', 'Impresora'), ('Cámara', 'Cámara'), ('Dron', 'Dron'), ('Electrodoméstico', 'Electrodoméstico'), ('Redes', 'Redes y Conectividad'), ('Almacenamiento', 'Almacenamiento'), ('Monitores', 'Monitores'), ('Componentes', 'Componentes de PC'), ('Smartwatch', 'Smartwatch / Wearables'), ('Audio', 'Audio y Sonido'), ('Proyector', 'Proyector'), ('Software', 'Software'), ('Energía', 'Energía / UPS / Baterías'), ('IoT', 'Internet de las Cosas (IoT)'), ('Domótica', 'Domótica'), ('Electrónica', 'Electrónica General'), ('Gaming', 'Gaming'), ('Cables', 'Cables y Adaptadores'), ('Cocina', 'Cocina Inteligente'), ('Oficina', 'Oficina y Periféricos'), ('Iluminación', 'Iluminación LED / Smart')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, choices=[('Samsung', 'Samsung'), ('LG', 'LG'), ('HP', 'HP'), ('Whirlpool', 'Whirlpool'), ('Xiaomi', 'Xiaomi'), ('Frigidaire', 'Frigidaire'), ('Mabe', 'Mabe'), ('Hisense', 'Hisense'), ('Apple', 'Apple'), ('Sony', 'Sony'), ('DELL', 'DELL'), ('Black+Decker', 'Black+Decker'), ('Motorola', 'Motorola'), ('Lenovo', 'Lenovo'), ('Honor', 'Honor'), ('Huawei', 'Huawei'), ('Nintendo', 'Nintendo'), ('Oster', 'Oster'), ('JBL', 'JBL'), ('KitchenAid', 'KitchenAid'), ('Toshiba', 'Toshiba'), ('Remington', 'Remington'), ('DJI', 'DJI'), ('Acer', 'Acer'), ('Panasonic', 'Panasonic'), ('Skullcandy', 'Skullcandy'), ('Garmin', 'Garmin'), ('Epson', 'Epson'), ('General Electric', 'General Electric'), ('Canon', 'Canon'), ('Microsoft', 'Microsoft'), ('Panamax', 'Panamax'), ('EnergyMax', 'EnergyMax'), ('Barkan', 'Barkan'), ('Aiwa', 'Aiwa'), ('iRobot', 'iRobot'), ('Taurus', 'Taurus'), ('Razer', 'Razer'), ('Logitech', 'Logitech'), ('Segway', 'Segway'), ('Cuisinart', 'Cuisinart'), ('Homedics', 'Homedics'), ('Karcher', 'Karcher'), ('APC', 'APC'), ('Zagg', 'Zagg'), ('Revlon', 'Revlon'), ('Klip Xtreme', 'Klip Xtreme'), ('Solo', 'Solo'), ('Forza', 'Forza'), ('Klip', 'Klip'), ('Midland', 'Midland'), ('Marshall', 'Marshall'), ('Tucano', 'Tucano'), ('Soportv', 'Soportv'), ('Xtech', 'Xtech'), ('Fitbit', 'Fitbit'), ('Salicru', 'Salicru'), ('Drinkmate', 'Drinkmate'), ('Thule', 'Thule'), ('Steren', 'Steren'), ('Navia', 'Navia'), ('George Foreman', 'George Foreman'), ('Nescafe Dolce Gusto', 'Nescafe Dolce Gusto'), ('KIDdesigns', 'KIDdesigns'), ('Delonghi', 'Delonghi'), ('Eset', 'Eset'), ('Holstein', 'Holstein'), ('Mybat', 'Mybat'), ('Wahl', 'Wahl'), ('Niu', 'Niu'), ('Casio', 'Casio'), ('Philips', 'Philips'), ('Wacom', 'Wacom'), ('Adam Elements', 'Adam Elements'), ('RCA', 'RCA'), ('Popsockets', 'Popsockets'), ('TP-LINK', 'TP-LINK'), ('Sandisk', 'Sandisk'), ('Vivitar', 'Vivitar'), ('Mr Coffee', 'Mr Coffee'), ('Dyson', 'Dyson'), ('Starlink', 'Starlink'), ('Totto', 'Totto'), ('ISDIN', 'ISDIN'), ('Brumate', 'Brumate'), ('Tocobo', 'Tocobo'), ('Skin 1004', 'Skin 1004'), ('Shark', 'Shark'), ('Bonefly', 'Bonefly'), ('Tec Italy', 'Tec Italy'), ('Tía Mía', 'Tía Mía'), ('Targus', 'Targus'), ('Ninja', 'Ninja')], max_length=20),
        ),
    ]
