# Generated by Django 5.2.7 on 2025-10-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_promocard_alter_carouselimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoPill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_html', models.CharField(max_length=180)),
                ('cta_text', models.CharField(default='Ver más', max_length=40)),
                ('enlace', models.URLField(blank=True)),
                ('variante', models.CharField(choices=[('default', 'Default'), ('soft', 'Soft')], default='default', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ['orden']},
        ),
    ]
