# Generated by Django 5.2.7 on 2025-10-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_promopill_alter_carouselimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promopill',
            name='filtro_brand',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='promopill',
            name='filtro_q',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
