# Generated by Django 5.2.7 on 2025-10-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
