# Generated by Django 5.2.7 on 2025-10-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorito_por', to='productos.producto'),
        ),
    ]
