# Generated by Django 5.2.7 on 2025-10-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_pedido_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Pago contra entrega')], max_length=20),
        ),
    ]
