# Generated by Django 5.2.7 on 2025-10-25 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_alter_pedido_tipo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nit', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia bancaria'), ('efectivo', 'Pago contra entrega')], max_length=20)),
                ('tarjeta_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('tarjeta_codigo', models.CharField(blank=True, max_length=5, null=True)),
                ('tarjeta_expira', models.CharField(blank=True, max_length=7, null=True)),
                ('transferencia_autorizacion', models.CharField(blank=True, max_length=30, null=True)),
                ('transferencia_cuenta', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
